### ISSUE TITLE
no `gnmi_set` found when running 'sudo make test'

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucetagent#1]
```
*** Starting controller
c0 Timeout waiting for FAUCET to start. Log:
Traceback (most recent call last):
  File "/usr/local/bin/faucet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/faucet/__main__.py", line 166, in main
    os.execvp(ryu_args[0], ryu_args)
  File "/usr/lib/python3.5/os.py", line 615, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.5/os.py", line 660, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/lib/python3.5/os.py", line 650, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory

*** Starting 2 switches
s1 s2 ...
* Shutting down any agents listening on 10161
* Starting agent
* Waiting for agent to start up
10161/tcp:          
* Sending test configuration to agent
Traceback (most recent call last):
  File "./agenttest.py", line 399, in <module>
    main()
  File "./agenttest.py", line 394, in main
    exit_code = end_to_end_test()
  File "./agenttest.py", line 349, in end_to_end_test
    result = run(cmd, stdout=PIPE, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'gnmi_set'
makefile:46: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by lantz** [comment]
Probably `GOPATH` isn't set correctly.  We  might want to change how it is set in `makefile`.

**Comment by cglewis** [comment]
I did this test on a system I didn't already have golang on, and this is the GOPATH it set for me:
```
GOPATH=/home/clewis/go PATH=/home/clewis/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin ./agenttest.py
```
Which is in fact where the code has been downloaded to:
```
~/go$ tree -d -L 3
.
└── src
    ├── github.com
    │   ├── golang
    │   ├── google
    │   ├── kylelemons
    │   └── openconfig
    ├── golang.org
    │   └── x
    └── google.golang.org
        ├── genproto
        └── grpc

11 directories
~/go$ pwd
/home/clewis/go
```
Should I be setting something else?

**Comment by lantz** [comment]
In the current agent version, both `makefile` and `dependencies.sh` should use the `GOPATH` that you have set, or `$HOME/go` if it isn't set.

**Comment by cglewis** [comment]
I pulled in the latest and ran `./dependencies.sh` and noticed this time it did this:
```
* Installing gnxi tools
package github.com/google/gnxi/gnmi_capabilities: cannot download, $GOPATH not set. For more details see: go help gopath
can't load package: package github.com/google/gnxi/gnmi_capabilities: cannot find package "github.com/google/gnxi/gnmi_capabilities" in any of:
	/usr/lib/go-1.6/src/github.com/google/gnxi/gnmi_capabilities (from $GOROOT)
	($GOPATH not set)
package github.com/google/gnxi/gnmi_get: cannot download, $GOPATH not set. For more details see: go help gopath
can't load package: package github.com/google/gnxi/gnmi_get: cannot find package "github.com/google/gnxi/gnmi_get" in any of:
	/usr/lib/go-1.6/src/github.com/google/gnxi/gnmi_get (from $GOROOT)
	($GOPATH not set)
package github.com/google/gnxi/gnmi_set: cannot download, $GOPATH not set. For more details see: go help gopath
can't load package: package github.com/google/gnxi/gnmi_set: cannot find package "github.com/google/gnxi/gnmi_set" in any of:
	/usr/lib/go-1.6/src/github.com/google/gnxi/gnmi_set (from $GOROOT)
	($GOPATH not set)
package github.com/google/gnxi/gnmi_target: cannot download, $GOPATH not set. For more details see: go help gopath
can't load package: package github.com/google/gnxi/gnmi_target: cannot find package "github.com/google/gnxi/gnmi_target" in any of:
	/usr/lib/go-1.6/src/github.com/google/gnxi/gnmi_target (from $GOROOT)
	($GOPATH not set)
* Installing FAUCET as root
* Done
```
It probably did that last time too, I just missed it. I added `export` in front of the `GOPATH` variable in the beginning of the script and it fixed the `GOPATH` issue, but resulted in this:
```
* Installing gnxi tools
package context: unrecognized import path "context" (import path does not begin with hostname)
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)
../../../go/src/google.golang.org/grpc/balancer.go:22:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/clewis/go/src/context (from $GOPATH)
../../../go/src/golang.org/x/net/http2/not_go111.go:10:2: cannot find package "net/http/httptrace" in any of:
	/usr/lib/go-1.6/src/net/http/httptrace (from $GOROOT)
	/home/clewis/go/src/net/http/httptrace (from $GOPATH)
package context: unrecognized import path "context" (import path does not begin with hostname)
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)
../../../go/src/google.golang.org/grpc/balancer.go:22:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/clewis/go/src/context (from $GOPATH)
../../../go/src/golang.org/x/net/http2/not_go111.go:10:2: cannot find package "net/http/httptrace" in any of:
	/usr/lib/go-1.6/src/net/http/httptrace (from $GOROOT)
	/home/clewis/go/src/net/http/httptrace (from $GOPATH)
package context: unrecognized import path "context" (import path does not begin with hostname)
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)
../../../go/src/google.golang.org/grpc/balancer.go:22:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/clewis/go/src/context (from $GOPATH)
../../../go/src/golang.org/x/net/http2/not_go111.go:10:2: cannot find package "net/http/httptrace" in any of:
	/usr/lib/go-1.6/src/net/http/httptrace (from $GOROOT)
	/home/clewis/go/src/net/http/httptrace (from $GOPATH)
package context: unrecognized import path "context" (import path does not begin with hostname)
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)
../../../go/src/google.golang.org/grpc/balancer.go:22:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/clewis/go/src/context (from $GOPATH)
../../../go/src/golang.org/x/net/http2/not_go111.go:10:2: cannot find package "net/http/httptrace" in any of:
	/usr/lib/go-1.6/src/net/http/httptrace (from $GOROOT)
	/home/clewis/go/src/net/http/httptrace (from $GOPATH)
* Installing FAUCET as root
* Done
```
For whatever reason it's angry about that context thing.

**Comment by lantz** [comment]
Well that is interesting. Last I checked, `dependencies.sh` actually sets `GOPATH` so it is odd that it isn't set.

    GOPATH=${GOPATH:=$HOME/go}

You can try running it wish `bash -x` to see why that line is being skipped and also which commands aren't working.

The problem could be that you have golang 1.7 and gnxi requires golang 1.7+.

**Comment by cglewis** [comment]
Hmm, interesting, I'm running Ubuntu 16.04 and it installed golang with apt get via the `dependencies.sh` script, so 1.6 must be the latest packaged release for 16.04.

**Comment by lantz** [comment]
Ah, maybe my script installed the distro version, which in this case is too old.

**Comment by cglewis** [comment]
I think travis pre-equips their instances with a bunch of stuff like python and golang so they run faster.

**Comment by lantz** [comment]
Hmm. I am thinking we might want to 

- `set -e` in the dependency scripts
- not set `GOPATH` so that a missing `GOPATH` will cause an error
- possibly check the go version to make sure it's 1.7+
- possibly move the go stuff into `test-dependencies.sh`

**Comment by lantz** [comment]
I think possibly removing your `GOPATH` directory and reinstalling might work.

**Comment by lantz** [comment]
I tested against go 1.6 in Ubuntu 16.04 and ran into the same `context` problem, so I think checking for `go version` >= `go 1.7` is correct.

**Comment by cglewis** [comment]
I updated to golang 1.12 and it fixed the gnxi/context issues.  There was however a few other things that cropped up.

1. had to run `./test-dependencies` with sudo for two of the pip installs
```
$ ./test-dependencies.sh 
* Installing testing (make {test,codecheck}) dependencies
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/pycodestyle.py'
Consider using the `--user` option or check the permissions.

/tmp/tmp.5q4u4jOzga ~/github/faucetagent
Cloning into 'mininet'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 9645 (delta 9), reused 23 (delta 6), pack-reused 9617
Receiving objects: 100% (9645/9645), 3.00 MiB | 5.62 MiB/s, done.
Resolving deltas: 100% (6393/6393), done.
Checking connectivity... done.
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/mininet-2.3.0d5.dist-info'
Consider using the `--user` option or check the permissions.
```

2. while the test got a lot farther this time, it still ultimately failed for me, and I'm not sure why:
```
$ sudo make test
GOPATH=/home/clewis/go PATH=/home/clewis/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin ./agenttest.py
* Generating certificates
* Generating fake CA cert
* Generating and signing fake server cert
* Generating fake client cert (self-signed)
* Starting network
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 h3 h4 
*** Adding switches:
s1 s2 
*** Adding links:
(s1, h1) (s1, h2) (s1, s2) (s2, h3) (s2, h4) 
*** Configuring hosts
h1 h2 h3 h4 
*** Starting controller
c0 Timeout waiting for FAUCET to start. Log:
Traceback (most recent call last):
  File "/usr/local/bin/faucet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/faucet/__main__.py", line 166, in main
    os.execvp(ryu_args[0], ryu_args)
  File "/usr/lib/python3.5/os.py", line 615, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.5/os.py", line 660, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/lib/python3.5/os.py", line 650, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory

*** Starting 2 switches
s1 s2 ...
* Shutting down any agents listening on 10161
* Starting agent
* Waiting for agent to start up
10161/tcp:          
* Sending test configuration to agent
F0410 17:02:51.057616     799 gnmi_set.go:160] Set failed: rpc error: code = Unknown desc = Exception calling application: Command '['fuser', '-k', '-HUP', '9302/tcp']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./agenttest.py", line 399, in <module>
    main()
  File "./agenttest.py", line 394, in main
    exit_code = end_to_end_test()
  File "./agenttest.py", line 349, in end_to_end_test
    result = run(cmd, stdout=PIPE, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['gnmi_set', '-ca', 'testcerts/fakeca.crt', '-cert', 'testcerts/fakeclient.crt', '-key', 'testcerts/fakeclient.key', '-target_name', 'localhost', '-replace=/:\nvlans:\n  office:\n    vid: 100\n  guest:\n    vid: 200\n\ndps:\n  s1:\n    dp_id: 0x1\n    hardware: "Open vSwitch"\n    interfaces:\n      1:\n        name: "h1"\n        native_vlan: office\n      2:\n        name: "h2"\n        native_vlan: guest\n      3:\n        name: "link"\n        tagged_vlans: [office, guest]\n  s2:\n    dp_id: 0x2\n    hardware: "Open vSwitch"\n    interfaces:\n      1:\n        name: "h3"\n        native_vlan: office\n      2:\n        name: "h4"\n        native_vlan: guest\n      3:\n        name: "link"\n        tagged_vlans: [office, guest]\n']' returned non-zero exit status 1
makefile:46: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by lantz** [comment]
I created PR #6 to address this.

**Comment by lantz** [comment]
This is astonishingly painful - of course it works fine in travis, but it would be nice to work for normal users also. ;-p

**Comment by cglewis** [comment]
Yeah, sorry for all of the back and forth. I also figured it if was passing in Travis it wouldn't be that hard to try out locally.

**Comment by lantz** [comment]
One kind of terrible thing is that mininet has to run as root (for now at least) which means that it can get a completely different python environment from the non-root environment. We'd like to be able to run `make codecheck` as non-root, but then it will fail if the non-root python environment doesn't have mininet installed in it...

**Comment by cglewis** [comment]
Tracked down why Faucet wasn't starting. I had set the permissions of the logs files wrong (I had been previously doing Faucet stuff on this box).  Once I fixed the permissions on the log file, the tests completed successfully!

**Comment by lantz** [comment]
Hmm, not sure why that would cause the test to fail actually since it runs faucet as root and logs to stdout.

However, if you are happy with the current state of #6, then maybe we can merge it and then close this issue.
